name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: us-east-1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t ve3_webapp:latest .
          docker tag ve3_webapp:latest 975050333781.dkr.ecr.us-east-1.amazonaws.com/ve3_webapp:latest
          docker push 975050333781.dkr.ecr.us-east-1.amazonaws.com/ve3_webapp:latest
        env:
          ECR_REGISTRY: 975050333781.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ve3_webapp
          IMAGE_TAG: latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to ECS
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: my-web-app-task:1
          service: my-web-service
          cluster: ve3-cluster
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

